### PR TITLE
UI change

### PR DESCRIPTION
**Pull request by OkenHaha**
Made some UI changes for the homepage. Merge it if it's ok : )

### CODE REVIEW

**Comment by himanshu1221** [comment]
> Made some UI changes for the homepage. Merge it if it's ok : )
hey Oken thanks for looking into this project it would be great if u fix the UI of your query box too ! 
Screenshot from 2023-01-25 22-59-41

**Comment by himanshu1221** [comment]
> Made some UI changes for the homepage. Merge it if it's ok : )

also please look into this home  screen responsivness it not looking that good 
Screenshot from 2023-01-25 23-03-06

**Comment by OkenHaha** [comment]
> > Made some UI changes for the homepage. Merge it if it's ok : )
> 
> also please look into this home screen responsivness it not looking that good Screenshot from 2023-01-25 23-03-06

Sure bud, I've been away so I didn't noticed this, will take a look

**Comment by himanshu1221** [comment]
hey @OkenHaha are you working on this issue ?

**Comment by OkenHaha** [comment]
> hey @OkenHaha are you working on this issue ?

Yeah, sorry bud, I've been working on a different project so I wasn't able to work on this. I'm occupied for today as well but I can work on it starting tomorrow, if that's ok with you.

**Comment by himanshu1221** [comment]
> > hey @OkenHaha are you working on this issue ?
> 
> Yeah, sorry bud, I've been working on a different project so I wasn't able to work on this. I'm occupied for today as well but I can work on it starting tomorrow, if that's ok with you.

sore man take your time !

**Pull request closed without merging**
